#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::home
create:
  path: /create
  controller: App\Controller\CreateController::create
redirect:
  path: /{code}
  controller: App\Controller\RedirectController::redirectFromCode